"""Added user_id to Vote model

Revision ID: fb701070b811
Revises: 
Create Date: 2025-02-03 16:20:03.926040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb701070b811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('recommended')

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('vote_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('vote_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
